services:
  wordpress:
    image: bitnami/wordpress:6.6.2-debian-12-r6
    ports:
      - 80:8080
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DB_HOST=mariadb
      - DB_NAME=wordpress
      - DB_PASSWORD=DatabaseFTW
      - DB_USER=wordpress
      - WORDPRESS_PASSWORD=testing123
      - WORDPRESS_USERNAME=admin@example.com
      - WP_DEBUG=true
      - PHP_MAX_EXECUTION_TIME=3000
      - PHP_MAX_INPUT_TIME=3000
      - PHP_MAX_INPUT_VARS=3000
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=2000M
      - PHP_UPLOAD_MAX_FILESIZE=2000M
    volumes:
      - ./wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
      
  mariadb:
    image: bitnami/mariadb:11.5.2-debian-12-r3
    volumes:
      - mariadb_data:/bitnami/mariadb/data
      - ./bin/custom-init.sql:/docker-entrypoint-initdb.d/custom-init.sql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_ROOT_PASSWORD=root_password
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
    expose:
      - 3306

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local